# Generated by Django 2.2.16 on 2022-02-06 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='filters',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='mailing',
            old_name='tags',
            new_name='tag',
        ),
    ]
